### ISSUE TITLE
timestamp generated in the report header is old

### ISSUE THREAD

**Issue by bheemreddy181** [dashingrocket/simplecov-cobertura#12]
The timestamp generated in report header seems wrong 

```
<?xml version='1.0'?> 
<!DOCTYPE coverage SYSTEM "http://cobertura.sourceforge.net/xml/coverage-04.dtd">
<!-- Generated by simplecov-cobertura version 1.3.1 (https://github.com/dashingrocket/simplecov-cobertura) -->
<coverage line-rate="1.0" branch-rate="0" lines-covered="226" lines-valid="226" branches-covered="0" branches-valid="0" complexity="0" version="0" timestamp="1476766800">
```

<img width="466" alt="Screen Shot 2020-07-14 at 09 57 38" src="https://user-images.githubusercontent.com/3464623/87441206-78d37600-c5b8-11ea-8373-435a54aaf93c.png">

**Comment by jessebs** [comment]
I am unable to recreate the problem.  Can you create a sample project that reproduces the problem?

The timestamp is generated by a call to `Time.now.to_i.to_s`.  Are you using timecop or mocking Time.now in your tests?

**Comment by bheemreddy181** [comment]
Thanks @jessebs it is because of the Timecop.freeze. It's working fine now.
