### ISSUE TITLE
Fix Deprecation Warning: The SimpleCov::Formatter::CoberturaFormatter formatter uses the deprecated formatter interface not supported directly by RSpec 3

### ISSUE THREAD

**Issue by zherr** [dashingrocket/simplecov-cobertura#7]
Full warning: 
```
Deprecation Warnings:

 The SimpleCov::Formatter::CoberturaFormatter formatter uses the deprecated formatter interface not supported directly by RSpec 3.  To continue to use this formatter you must install the `rspec-legacy_formatters` gem, which provides support for legacy formatters or upgrade the formatter to a compatible version.  Formatter added at: /Users/my-user/.rvm/gems/ruby-2.5.1@app/gems/rspec-core-3.7.1/exe/rspec:4:in `<top (required)>'


If you need more of the backtrace for any of these deprecations to
identify where to make the necessary changes, you can configure
`config.raise_errors_for_deprecations!`, and it will turn the
deprecation warnings into errors, giving you the full backtrace.

1 deprecation warning total
```

Reproduction steps:
1. Everything in the README
2. Rspec v3 or greater
3. Run `bundle exec rspec --format SimpleCov::Formatter::CoberturaFormatter`

**Comment by jessebs** [comment]
Any chance you tar up a sample project that produces the issue?

**Comment by jessebs** [comment]
The spec file below produces a coverage report in both rspec v2 and v3 with no warning.
`
require 'simplecov'
require 'simplecov-cobertura'

SimpleCov.formatter = SimpleCov::Formatter::CoberturaFormatter
SimpleCov.start

require_relative '../lib/blah'

RSpec.describe "something" do
  it "does something" do
  end
end`

Running your example command provides a different error for me, so I cannot reproduce your original issue

**Comment by zherr** [comment]
Yes! Check this out: 
[bug-7.zip](https://github.com/dashingrocket/simplecov-cobertura/files/2985889/bug-7.zip)

Once in the project directory, run:
```
bundle install
bundle exec rspec --format SimpleCov::Formatter::CoberturaFormatter
```

And you should see the warning.

**Comment by jessebs** [comment]
The --format flag of rspec is to indicate the format of the rspec output.  The simplecov cobertura formatter is NOT an rspec formatter, but is a simplecov formatter.

If you just run the following from your sample project, you will see the simplecov output in coverage/coverage.xml
`bundle exec rspec`

**Comment by zherr** [comment]
Thanks @jessebs , you're right! User error. Closing!
